export const legalPages = {
  privacy: {
    title: "Privacy Policy",
    body: [
      "Last Updated: 25-06-2026",
      "1. Information We Collect",
      "The application may collect information necessary to provide authentication, onboarding, platform access, communication features, feedback systems, analytics, and related functionality.",
      "Account and Authentication Information",
      "When users sign in using supported authentication providers (such as Google Sign-In or Firebase Authentication), the application may receive and store: Name, Email address, User ID or authentication provider ID, Profile photo URL, if available, Authentication/session status, User role or account type, Account timestamps.",
      "Authentication providers may also process technical information such as IP address, browser/device information, authentication tokens, and security logs.",
      "User Profile and Onboarding Information",
      "Depending on application features, the platform may collect: Registration or identification numbers, Organization, institution, department, class, or section information, Onboarding status, User-entered profile information, Account preferences and settings.",
      "Admin and Access Request Information",
      "For users requesting elevated access, the application may collect: Designation or role, Organization or department, Reason for requesting access, Approval/request status, Related timestamps.",
      "Authorized administrators may also be associated with platform management activities.",
      "Feedback and Usage Information",
      "If users submit feedback or support requests, the application may collect: Ratings or survey responses, Written feedback/comments, Submission timestamps, User identifiers associated with submissions.",
      "The application may also process technical and analytics information such as: IP address, Browser/device information, Page visits and usage activity, Error or performance logs, Approximate location inferred from network information.",
      "This information is used for reliability, analytics, security, abuse prevention, and platform improvement.",
      "2. How We Use Information",
      "Collected information may be used to: Authenticate users securely, Maintain user sessions and profiles, Provide platform features and content, Manage onboarding and access requests, Deliver announcements, schedules, events, and communications, Improve user experience and application performance, Process feedback and support requests, Store user preferences, Prevent abuse, fraud, or unauthorized access.",
      "3. Information We Do Not Intentionally Collect",
      "Unless specifically required for application functionality, the application does not intentionally collect: Payment or banking information, Government-issued identity documents, Precise GPS location data, Contact lists or phone contacts, Health or biometric information, Passwords for third-party authentication providers.",
      "The application does not sell or rent personal information",
      "4. Third-Party Services",
      "The application may rely on third-party providers for authentication, hosting, storage, analytics, notifications, or infrastructure services.",
      "Examples may include: Firebase, Google Cloud, Vercel.",
      "These providers may process technical and account-related information according to their own privacy and security practices.",
      "5. Cookies, Local Storage, and Browser Technologies",
      "The application may use cookies, local storage, IndexedDB, authentication tokens, or similar browser technologies for: Keeping users signed in, Remembering preferences, Supporting offline functionality, Improving performance and reliability, Maintaining security and session integrity.",
      "Disabling or clearing browser storage may affect application functionality.",
      "6. Data Storage and Retention",
      "User information may be stored using cloud databases, authentication providers, and infrastructure services.",
      "Information may be retained only as long as reasonably necessary to: Provide platform functionality, Maintain user accounts and roles, Support operational and security requirements, Preserve necessary records and logs.",
      "Deleted data may temporarily remain in backups or provider systems according to infrastructure retention practices.",
      "7. Security Practices",
      "The application uses reasonable technical and organizational measures designed to protect information from unauthorized access, disclosure, misuse, or alteration.",
      "Security measures may include: Authentication systems, Role-based access controls, Database security rules, Secure communication protocols, Administrative access restrictions.",
      "No system can guarantee complete security.",
      "8. Administrative Access and Visibility",
      "Authorized administrators may access information reasonably necessary to operate and manage the platform, including: User profile information, Administrative workflow data, Content and configuration management data, Feedback and support submissions.",
      "Administrative access should be limited to authorized personnel and used only for legitimate operational purposes.",
      "9. Sharing and Disclosure",
      "The application does not sell user information.",
      "Information may be shared only in limited circumstances, including: With service providers necessary to operate the platform, With authorized administrators, To comply with legal obligations or lawful requests, To protect platform security, integrity, users, or organizational interests.",
      "10. User Rights and Choices",
      "Depending on applicable laws and platform policies, users may request: Access to their personal information, Correction of inaccurate information, Deletion of personal information where feasible, Information about how their data is used.",
      "The platform may verify user identity before processing requests.",
      "11. Changes to This Privacy Policy",
      "This Privacy Policy may be updated periodically to reflect changes in platform features, third-party services, legal requirements, or operational practices.",
      "The “Last Updated” date indicates when the policy was most recently revised."
    ]
  },
  terms: {
    title: "Terms of Service",
    body: [
      "Last Updated: 25-06-2026",
      "These Terms of Service govern your access to and use of the application, website, platform, and related services provided by Developer’s Society.",
      "By accessing or using the application, you agree to comply with these Terms. If you do not agree with these Terms, you should not use the application.",
      "1. Use of the Application",
      "The application is intended to provide digital services, communication features, schedules, announcements, events, productivity tools, community features, or related platform functionality.",
      "You agree to use the application only for lawful purposes and in a manner that does not interfere with the security, availability, or proper functioning of the platform.",
      "2. User Accounts",
      "Some features may require users to create or sign in to an account using supported authentication providers such as Google Sign-In or similar services.",
      "Users are responsible for: Providing accurate account information, Maintaining the security of their account, Using the platform responsibly, Restricting unauthorized access to their account.",
      "The application may suspend, restrict, or remove accounts that violate these Terms or misuse the platform.",
      "3. Acceptable Use",
      "Users must not: Violate applicable laws or regulations, Attempt unauthorized access to systems or accounts, Disrupt, overload, or damage platform infrastructure, Upload or distribute malicious software or harmful content, Misrepresent identity, role, or affiliation, Use the platform for harassment, abuse, spam, or fraudulent activity, Attempt to bypass security or access restrictions.",
      "Administrative or moderator privileges may be revoked for misuse or unauthorized activity.",
      "4. Content and Platform Management",
      "The platform may allow administrators, moderators, or authorized users to create, manage, or publish content such as announcements, schedules, events, groups, or communications.",
      "Developer’s Society reserves the right to: Remove or modify content, Restrict platform access, Review reported activity, Suspend features or accounts when necessary for security, operational, or policy reasons.",
      "5. Third-Party Services",
      "The application may rely on third-party services for authentication, hosting, analytics, storage, notifications, or infrastructure functionality.",
      "Examples may include: Firebase, Google Cloud, Vercel.",
      "Use of such services may also be subject to the terms and privacy policies of those providers.",
      "6. Intellectual Property",
      "Unless otherwise stated, the application, branding, logos, interface designs, software, and related content are owned by or licensed to Developer’s Society.",
      "Users may not: Copy, distribute, modify, or reverse engineer the platform, Reuse platform branding without permission, Attempt to extract source code or proprietary systems except where permitted by law.",
      "7. Privacy",
      "Use of the application is also governed by the associated Privacy Policy, which explains how information may be collected, used, and stored.",
      "By using the application, you acknowledge that you have reviewed the Privacy Policy.",
      "8. Availability and Changes",
      "The application may be updated, modified, suspended, or discontinued at any time without prior notice.",
      "Features, services, integrations, or access requirements may change as the platform evolves.",
      "The developers or organization are not responsible for temporary outages, maintenance interruptions, or technical issues beyond reasonable control.",
      "9. Disclaimer of Warranties",
      "The application is provided on an “as is” and “as available” basis without warranties of any kind, whether express or implied.",
      "Developer’s Society does not guarantee that: The platform will always be available or error-free, Information provided through the platform will always be accurate or complete, The platform will be free from security vulnerabilities or interruptions.",
      "Users access and use the platform at their own risk.",
      "10. Limitation of Liability",
      "To the maximum extent permitted by applicable law, Developer’s Society shall not be liable for: Indirect or consequential damages, Data loss or service interruptions, Unauthorized access to accounts or data, Issues caused by third-party services or infrastructure providers, User-generated content or misuse of the platform.",
      "11. Termination",
      "The application may suspend or terminate access to users who: Violate these Terms, Misuse platform resources, Engage in unauthorized or harmful activity, Create security or operational risks.",
      "Users may also stop using the platform at any time.",
      "12. Changes to These Terms",
      "These Terms may be updated periodically to reflect changes in: Platform functionality, Legal or operational requirements, Security practices, Third-party integrations.",
      "Continued use of the platform after updates constitutes acceptance of the revised Terms.",
      "13. Governing Rules",
      "These Terms shall be governed by and interpreted according to applicable laws, institutional policies, and organizational guidelines relevant to the operation of the platform."
    ]
  }
} as const;

export type LegalSlug = keyof typeof legalPages;
